name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  check-pr-title:
    name: Check pull request title
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate PR title
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          if [[ ! $PR_TITLE =~ ^#[0-9]+ ]]; then
            echo "❌ Error: PR title must start with an issue number (e.g., '#123 Fix bug'). Current title: '$PR_TITLE'"
            exit 1
          else
            echo "✅ PR title is valid: $PR_TITLE"
          fi

  backend-build-and-format:
    name: Backend Build and Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build python3-pip zlib1g-dev libuv1-dev
          pip3 install meson

      - name: Install clang-format-20
        run: |
          wget https://github.com/llvm/llvm-project/releases/download/llvmorg-20.1.2/clang+llvm-20.1.2-x86_64-linux-gnu-ubuntu-22.04.tar.xz
          tar -xJf clang+llvm-20.1.2-x86_64-linux-gnu-ubuntu-22.04.tar.xz
          sudo cp clang+llvm-20.1.2-x86_64-linux-gnu-ubuntu-22.04/bin/clang-format /usr/local/bin/clang-format
          sudo chmod +x /usr/local/bin/clang-format
          clang-format --version  # Should show 20.1.2

      - name: Check C++ formatting
        run: |
          cd server
          find src include -name '*.cpp' -o -name '*.h' | xargs clang-format -n --Werror --style=file
        env:
          CLANG_FORMAT_STYLE: file

      - name: Configure Meson
        run: |
          cd server
          meson setup build

      - name: Build backend
        run: |
          cd server
          meson compile -C build

  frontend-build-and-format:
    name: Frontend Build and Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: client/package.json

      - name: Install dependencies
        run: |
          cd client
          npm ci

      - name: Check formatting
        run: |
          cd client
          npm run format:check

      - name: Build frontend
        run: |
          cd client
          npm run build

# Generated by grok 3 lol 🥶
