name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-pr-title:
    name: Check pull request title
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Get latest PR title via GitHub API
        id: prtitle
        run: |
          pr_url="${{ github.event.pull_request.url }}"
          pr_title=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                           -H "Accept: application/vnd.github+json" \
                           "$pr_url" | jq -r .title)
          echo "PR Title: $pr_title"
          echo "pr_title=$pr_title" >> "$GITHUB_OUTPUT"

      - name: Validate PR title
        run: |
          PR_TITLE="${{ steps.prtitle.outputs.pr_title }}"
          echo "Validating PR title: $PR_TITLE"
          if [[ ! "$PR_TITLE" =~ ^#[0-9]+ ]]; then
            echo "❌ Error: PR title must start with an issue number (e.g., '#123 Fix bug'). Current title: '$PR_TITLE'"
            exit 1
          else
            echo "✅ PR title is valid: $PR_TITLE"
          fi

  backend-build-lint-format:
    name: Backend Build, lint and Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build python3-pip zlib1g-dev libuv1-dev
          pip3 install meson

      - name: Install clang-format-20
        run: |
          wget https://github.com/llvm/llvm-project/releases/download/llvmorg-20.1.2/LLVM-20.1.2-Linux-X64.tar.xz
          tar -xJf LLVM-20.1.2-Linux-X64.tar.xz
          sudo cp LLVM-20.1.2-Linux-X64/bin/clang-format /usr/local/bin/
          sudo chmod +x /usr/local/bin/clang-format
          clang-format --version  # Should show 20.1.2

      - name: Check C++ formatting
        run: |
          cd server
          find src include -name '*.cpp' -o -name '*.h' | xargs clang-format -n --Werror --style=file
        env:
          CLANG_FORMAT_STYLE: file

      - name: Lint C++
        run: |
          cd server
          find src include -type f \( -name '*.cpp' -o -name '*.hpp' \) -print0 | xargs -0 -P$(nproc) -I{} clang-tidy -p build {} -- -Iinclude

      - name: Configure Meson
        run: |
          cd server
          meson setup build -DuSockets:libuv=true

      - name: Build backend
        run: |
          cd server
          meson compile -C build

  frontend-build-and-format:
    name: Frontend Build and Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: client/package.json

      - name: Install dependencies
        run: |
          cd client
          npm ci

      - name: Check formatting
        run: |
          cd client
          npm run format:check

      - name: Build frontend
        run: |
          cd client
          npm run build

# Generated by grok 3 lol 🥶
